name: Build Configurator

# Controls when the workflow will run
on:
  push:
    branches: 
      - master
      - development
  pull_request:
    branches:
      - master
      - development
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build
  Build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-latest']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: build
        uses: ./.github/actions/build-pyinstaller
        with: 
          path: '${{ github.workspace }}'
        
      - uses: actions/upload-artifact@v2
        with:
          name: OpenFFBoard-Configurator-${{ matrix.os }}
          path: ${{ steps.build.outputs.distpath }}
          if-no-files-found: error
