name: Build Configurator

# Controls when the workflow will run
on:
  push:
    branches: 
      - master
      - development
  pull_request:
    branches:
      - master
      - development
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build
  Build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.conf.os }}
    strategy:
      fail-fast: false
      matrix:
        conf:  [ {os: 'windows-latest', pyver: '3.8'},{os: 'windows-latest', pyver: '3.12'}, {os: 'macos-latest', pyver: '3.11'}]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - id: build
        uses: ./.github/actions/build-pyinstaller
        with: 
          path: '${{ github.workspace }}'
          python-version: '${{ matrix.conf.pyver }}'
        
      - uses: actions/upload-artifact@v4
        with:
          name: OpenFFBoard-Configurator-${{ matrix.conf.os }}-py${{ matrix.conf.pyver }}
          path: ${{ steps.build.outputs.distpath }}
          if-no-files-found: error
