name: Release Configurator

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    uses: ./.github/workflows/build.yml
 
  Release:
    needs: [Build] # Requires build first
    name: Create release
    runs-on: ubuntu-latest

    steps:
    # Checkout  
      - uses: actions/checkout@v2

      # Download artifacts for release
      - uses: actions/download-artifact@v3
        with:
          path: etc/usr/artifacts/

      - name: Zip output
        run: for i in */; do zip -r "${i%/}.zip" "$i"; done
        working-directory: etc/usr/artifacts/

      # Create release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "Configurator ${{github.ref_name}}"
          body_path: ${{ github.workspace }}/CHANGELOG.md
          body: "Release notes coming soon"
          files: etc/usr/artifacts/*.zip
          prerelease: ${{contains(github.ref_name, '-')}}